status = [
    "Audit",
    "Code lint",
    "Test on linux",
    "Test on linux-arm",
    "Test on macos",
    "Test on windows"
]
required_approvals = 1
timeout_sec = 7200
delete_merged_branches = true 
